version: "3"
services:
  mysql:
    build: ./db/
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    image: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306