version: "3"
services:
  mysql:
    build: ./containers/db/
    volumes:
      - ./containers/db:/docker-entrypoint-initdb.d
    image: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306